In [1]:
import numpy as np
arr = np.arange(20)

In [2]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
#Function 01
arr.sum()

190

In [5]:
#Function 02
arr.min()

0

In [6]:
#Function 03
arr.max()

19

In [9]:
#Function 04
arr.argmin()

0

In [10]:
#Function 05
arr.argmax()

19

In [11]:
#Function 06
np.all([True, True, False, True])

False

In [12]:
#Function 07
np.any([False,True,False,False])

True

In [14]:
#Function 08
arr = np.zeros((10,10))
np.any(arr!=0)

False

In [15]:
#Function 08
arr = np.zeros((10,10))
np.any(arr==0)

True

In [16]:
#Function 08
arr = np.zeros((10,10))
np.all(arr==0)

True

In [17]:
#Function 09
arr = np.eye(5)

In [18]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#Function 10
arr = np.diag([1,1,1,1])
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
#Function 11
np.diag(arr)

array([1, 1, 1, 1])

In [23]:
#Function 12
arr = np.random.rand(10)
arr

array([0.35197196, 0.05540201, 0.70390353, 0.83529727, 0.88469427,
       0.750847  , 0.339492  , 0.77838266, 0.93085265, 0.61803077])

In [25]:
#Function 13
arr = np.random.randint(1,10,10)
arr

array([1, 5, 5, 1, 1, 8, 9, 3, 1, 6])

In [26]:
#Function 14
arr = np.arange(1,20,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [27]:
#Function 15
np.sin(20)

0.9129452507276277

In [28]:
#Function 16
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.6569866 , -0.54402111,  0.42016704,
       -0.28790332,  0.14987721])

In [29]:
#Function 17
arr = np.arange(10)
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [31]:
#Function 18
np.round(32374.2356434,2)

32374.24

In [34]:
#Function 19
arr = np.array([2.5, 5.9, -2.1, 8.3, 3.0, 8.5])
np.floor(arr)

array([ 2.,  5., -3.,  8.,  3.,  8.])

In [35]:
#Function 20
arr = np.array([2.5, 5.9, -2.1, 8.3, 3.0, 8.5])
np.ceil(arr)

array([ 3.,  6., -2.,  9.,  3.,  9.])

In [36]:
#Function 21
arr = np.array([2.5, 5.9, -2.1, 8.3, 3.0, 8.5])
np.trunc(arr)

array([ 2.,  5., -2.,  8.,  3.,  8.])

In [37]:
#Function 22
np.prod([[1.,2.],[3.,4.]])

24.0

In [40]:
#Function 23
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.cumsum(arr,axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [42]:
#Function 24
np.lcm(40,56)

280

In [43]:
#Function 25
np.gcd(2,8)

2

In [50]:
#Function 26
arr = np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
#Function 27
np.transpose(arr)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [52]:
#Function 28
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4');c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [53]:
np.char.capitalize(c)

array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

In [56]:
#Function 29
c = np.array(['A1BC', 'DEF', '123A']) 
np.char.lower(c)

array(['a1bc', 'def', '123a'], dtype='<U4')

In [58]:
#Function 30
np.char.upper(c)

array(['A1BC', 'DEF', '123A'], dtype='<U4')

In [61]:
#Function 31
np.char.count(c,'A')

array([1, 0, 1])

In [62]:
#Function 32
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [63]:
#Function 33
arr = np.random.randint(1,10,9).reshape(3,3)
arr

array([[3, 5, 8],
       [9, 3, 5],
       [8, 9, 5]])

In [64]:
#Function 34
np.min(arr, axis=1)

array([3, 3, 5])

In [65]:
#Function 35
np.max(arr, axis=1)

array([8, 9, 9])

In [66]:
#Function 36
np.min(arr, axis=0)

array([3, 3, 5])

In [67]:
#Function 37
np.max(arr, axis=0)

array([9, 9, 8])

In [68]:
#Function 38
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.random.shuffle(arr)
arr

array([2, 3, 0, 6, 5, 8, 9, 4, 1, 7])

In [72]:
#Function 39
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
#Function 40
arr = np.array([1,4,8,2])
arr.argsort()

array([0, 3, 1, 2], dtype=int64)

In [77]:
#Function 41
a=[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
np.where(arr<6)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [79]:
#Function 42
np.count_nonzero(arr)

9

In [81]:
#Function 43
arr = np.array([1,4,8,2])
arr.sort(axis=0)
arr

array([1, 2, 4, 8])

In [83]:
#Function 44
arr = np.arange(21)
np.split(arr, 3)

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20])]

In [85]:
#Function 45
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.delete(a,0,0)

array([[4, 5, 6],
       [7, 8, 9]])

In [93]:
#Function 46
np.insert(a,1,2)

array([1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
#Function 47
arr = np.diag([1,1,1,1])
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [95]:
np.fliplr(arr)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [97]:
#Function 48
np.flipud(arr)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [98]:
#Function 49
a = np.array([1,2,3])
b = np.array([5,1,20])
np.inner(a, b)

67

In [99]:
#Function 50
np.reciprocal(8.0)

0.125